import numpy as np
from math import log

# a=np.array([[1,2,1],[4,5,6],[8,9,3]])
# print("a=",a)
# print("a.shape=",a.shape)
# print("np.argmax(a,axis=0):",np.argmax(a,axis=0))
# print("np.argmax(a,axis=1):",np.argmax(a,axis=1))
# print(log(2.718281828459))
x = np.arange(-5, 5, 1)
x=np.reshape(x,(10,1))
print(x.shape)
y = np.arange(-5, 5, 1)
y=np.reshape(y,(10,1))
print(y)
# x, y = np.meshgrid(x, y)
# print(x)
# print(y)
# print(x-1)
print(np.concatenate((x,y),axis=1).shape)
a=np.arange(-2,2,1).reshape(1,4)
print(a.shape)
b=np.tile(a,(5,1))
print(b)
